name: tendermint-ut

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/setup-go@v2
      - name: Set GOBIN
        run: |
          echo "GOBIN=$(go env GOPATH)/bin" >> $GITHUB_ENV
      - uses: actions/checkout@v2.3.4
      - name: install
        run: cd ./libs/tendermint && make install install_abci && cd -
      # Cache bin
      - uses: actions/cache@v1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-tm-binary

  tm-consensus:
    name: tm-consensus tests
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Go Test consensus/
        run: go test $(go list ./libs/tendermint/consensus/... |grep -v commont_test.go) -timeout 20m
  tm-lite:
    name: tm-lite tests
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Go Test lite/
        run:  go test -count=1 ./libs/tendermint/lite/...
  tm-async:
    name: tm-async tests
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Go Test libs/async
        run: go test -count=1 -ldflags -s $(go list ./... | grep libs/async)

  tm-mempool:
    name: tm-mempool tests
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Go Test mempool/
        id: first-attempt
        run: go test -count=1 ./libs/tendermint/mempool/...
        continue-on-error: true
      - name: Go Test mempool Retry again on failure
        id: second-attempt
        if: steps.first_attempt.outcome != 'success'
        run: go test -count=1 ./libs/tendermint/mempool/...
        continue-on-error: true
      - name: Go Test mempool Retry again on failure
        id: third-attempt
        if: steps.second-attempt.outcome != 'success'
        run: go test -count=1 ./libs/tendermint/mempool/...
        continue-on-error: true
      - name: Go Test mempool Retry again on failure
        id: fourth-attempt
        if: steps.third-attempt.outcome != 'success'
        run: go test -count=1 ./libs/tendermint/mempool/...

  test_abci_apps:
    name: abci_apps tests
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/setup-go@v2
      - name: Set GOBIN
        run: |
          echo "GOBIN=$(go env GOPATH)/bin" >> $GITHUB_ENV
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-tm-binary
      - name: test_abci_apps
        run: ./libs/tendermint/abci/tests/test_app/test.sh
        shell: bash

  test_abci_cli:
    name: abci_cli tests
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/setup-go@v2
      - name: Set GOBIN
        run: |
          echo "GOBIN=$(go env GOPATH)/bin" >> $GITHUB_ENV
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-tm-binary
      - run: ./libs/tendermint/abci/tests/test_cli/test.sh
        shell: bash
