name: tendermint-ut 

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - uses: actions/setup-go@v2
      - name: Set GOBIN
        run: |
          echo "GOBIN=$(go env GOPATH)/bin" >> $GITHUB_ENV
      - uses: actions/checkout@v2.3.4
      - name: install
        run: make install install_abci
      # Cache bin
      - uses: actions/cache@v1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-tm-binary

  tm-core:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/setup-go@v2

      - name: test_tm_core
        run: |
       	  go test -count=1 -ldflags ./libs/tendermint/libs/async/... 
          go test -count=1 ./libs/tendermint/lite/...
          go test -count=1 ./libs/tendermint/mempool/...
          go test -count=1 ./libs/tendermint/consensus/...

  test_abci_apps:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/setup-go@v2
      - name: Set GOBIN
        run: |
          echo "GOBIN=$(go env GOPATH)/bin" >> $GITHUB_ENV
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-tm-binary
      - name: test_abci_apps
        run: ./libs/tendermint/abci/tests/test_app/test.sh
        shell: bash

  test_abci_cli:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/setup-go@v2
      - name: Set GOBIN
        run: |
          echo "GOBIN=$(go env GOPATH)/bin" >> $GITHUB_ENV
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v1
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-tm-binary
      - run: ./libs/tendermint/abci/tests/test_cli/test.sh
        shell: bash
